const inspirationalPhrases = [
    "Cada vez que evito morderme las uñas, estoy un paso más cerca de alcanzar mis metas.",
    "Mis uñas son una manifestación de mi fuerza interior y autocontrol.",
    "Cada vez que resisto la tentación de morderme las uñas, estoy fortaleciendo mi voluntad.",
    "Mis manos merecen ser tratadas con cuidado y respeto.",
    "Cada uña intacta es un recordatorio de mi capacidad para superar los malos hábitos.",
    "El camino hacia el éxito está pavimentado con pequeñas victorias sobre mí mismo.",
    "Al dejar de morderme las uñas, estoy cuidando mi salud física y mental.",
    "Mis uñas son una obra de arte en progreso; no voy a permitir que se arruinen.",
    "Cada vez que me resisto a la tentación, me siento más empoderado.",
    "Mis manos son herramientas poderosas que merecen ser tratadas con amor y cuidado.",
    "Cada día que pasa sin morderme las uñas, me acerco más a convertirme en la mejor versión de mí mismo.",
    "La paciencia y la perseverancia son clave para superar cualquier mal hábito, incluido el de morderse las uñas.",
    "Cada vez que siento la tentación, recuerdo que soy más fuerte que mi impulso.",
    "Mis uñas son un reflejo de mi autoestima; merecen ser cuidadas y respetadas.",
    "El proceso de dejar de morderme las uñas es un viaje hacia el autodescubrimiento y el crecimiento personal.",
    "Cada uña intacta es un pequeño logro que me acerca a una mayor confianza en mí mismo.",
    "Al cuidar mis uñas, estoy demostrando amor propio y autodisciplina.",
    "La gratificación de tener unas uñas sanas y bonitas supera con creces la gratificación momentánea de morderlas.",
    "Cada día sin morderme las uñas es una pequeña victoria que me impulsa hacia adelante.",
    "La determinación es la llave que abre la puerta hacia una vida libre de malos hábitos.",
    "Mis manos son mi carta de presentación al mundo; quiero que reflejen mi dedicación y cuidado personal.",
    "Cada uña que crece sin ser mordida es un recordatorio de mi capacidad para cambiar y mejorar.",
    "Al dejar de morderme las uñas, estoy liberando espacio para que florezcan nuevas oportunidades en mi vida.",
    "Cada vez que resisto la tentación, estoy fortaleciendo mi autoestima y mi confianza en mí mismo.",
    "El autodominio es la llave maestra que abre las puertas hacia una vida plena y satisfactoria.",
    "Mis uñas son como pequeñas obras de arte que merecen ser admiradas, no destruidas.",
    "Cada vez que me abstengo de morderme las uñas, estoy mostrando respeto hacia mí mismo y hacia mi cuerpo.",
    "La belleza de unas uñas sanas y bien cuidadas supera cualquier impulso momentáneo de morderlas.",
    "Al dejar de morderme las uñas, estoy reafirmando mi compromiso con mi bienestar físico y emocional.",
    "Mis manos son herramientas poderosas que merecen ser tratadas con amor y respeto; dejar de morderme las uñas es un acto de amor propio."
];

export default inspirationalPhrases;