const consejos = [
  "Identifica tus triggers: ¿Cuándo y por qué te muerdes las uñas?",
  "Mantén tus uñas cortas y limpias para reducir la tentación",
  "Usa un esmalte de uñas desagradable para disuadirte",
  "Practica la meditación y la relajación para reducir el estrés",
  "Desarrolla un hábito alternativo, como tocar un objeto o hacer un ejercicio",
  "Usa un brazalete o pulsera para recordarte no morderte las uñas",
  "Mantén las manos ocupadas con una actividad creativa",
  "Evita situaciones que te hagan sentir ansiedad o estrés",
  "Aprende a reconocer y manejar tus emociones",
  "Usa un aceite o crema para las uñas que tenga un sabor desagradable",
  "Practica la respiración profunda y lenta para calmarte",
  "Desarrolla una rutina diaria para mantener tus uñas saludables",
  "Usa un aplicador de uñas para mantenerlas limpias y secas",
  "Evita morderte las uñas cuando estés aburrido o cansado",
  "Practica la visualización para imaginar tus uñas saludables",
  "Usa un diario para registrar tus progresos y retrocesos",
  "Desarrolla una red de apoyo con amigos y familiares",
  "Aprende a decir 'no' a situaciones que te hagan sentir estrés",
  "Usa un objeto para distraerte, como un juguete o un objeto de fidget",
  "Practica la gratitud para enfocarte en lo positivo",
  "Desarrolla un plan de acción para situaciones difíciles",
  "Usa un espejo para recordarte la importancia de cuidar tus uñas",
  "Aprende a manejar la ansiedad y el estrés de manera saludable",
  "Desarrolla una rutina de cuidado personal para sentirte más seguro",
  "Usa un objeto para mantener tus manos ocupadas, como un lápiz o un bolígrafo",
  "Practica la auto-reflexión para entender tus motivaciones",
  "Desarrolla un hábito de ejercicio regular para reducir el estrés",
  "Usa un objeto para recordarte tus logros y progresos",
  "Aprende a perdonarte a ti mismo cuando cometas un error",
  "Desarrolla una rutina de relajación antes de dormir",
  "Usa un objeto para distraerte, como un libro o un juego",
  "Practica la auto-aceptación para amarte a ti mismo",
  "Desarrolla un plan de acción para situaciones de estrés",
  "Usa un objeto para recordarte la importancia de cuidar tus uñas",
  "Aprende a manejar la frustración de manera saludable",
  "Desarrolla un hábito de gratitud para enfocarte en lo positivo"
];

export default consejos;